import type { Wilaya } from './types.js';

/**
 * The 69 Algerian wilayas (provinces) by 2-digit code → French name.
 * Codes 49–58 were created by the 2019 reform; codes 59–69 by loi n° 26-06
 * (JO, 4 April 2026), which raised the count from 58 to 69.
 */
export const WILAYAS: Record<string, string> = {
  '01': 'Adrar',
  '02': 'Chlef',
  '03': 'Laghouat',
  '04': 'Oum El Bouaghi',
  '05': 'Batna',
  '06': 'Béjaïa',
  '07': 'Biskra',
  '08': 'Béchar',
  '09': 'Blida',
  '10': 'Bouira',
  '11': 'Tamanrasset',
  '12': 'Tébessa',
  '13': 'Tlemcen',
  '14': 'Tiaret',
  '15': 'Tizi Ouzou',
  '16': 'Alger',
  '17': 'Djelfa',
  '18': 'Jijel',
  '19': 'Sétif',
  '20': 'Saïda',
  '21': 'Skikda',
  '22': 'Sidi Bel Abbès',
  '23': 'Annaba',
  '24': 'Guelma',
  '25': 'Constantine',
  '26': 'Médéa',
  '27': 'Mostaganem',
  '28': "M'Sila",
  '29': 'Mascara',
  '30': 'Ouargla',
  '31': 'Oran',
  '32': 'El Bayadh',
  '33': 'Illizi',
  '34': 'Bordj Bou Arréridj',
  '35': 'Boumerdès',
  '36': 'El Tarf',
  '37': 'Tindouf',
  '38': 'Tissemsilt',
  '39': 'El Oued',
  '40': 'Khenchela',
  '41': 'Souk Ahras',
  '42': 'Tipaza',
  '43': 'Mila',
  '44': 'Aïn Defla',
  '45': 'Naâma',
  '46': 'Aïn Témouchent',
  '47': 'Ghardaïa',
  '48': 'Relizane',
  '49': "El M'Ghair",
  '50': 'El Meniaa',
  '51': 'Ouled Djellal',
  '52': 'Bordj Badji Mokhtar',
  '53': 'Béni Abbès',
  '54': 'Timimoun',
  '55': 'Touggourt',
  '56': 'Djanet',
  '57': 'In Salah',
  '58': 'In Guezzam',
  '59': 'Aflou',
  '60': 'Barika',
  '61': 'Ksar Chellala',
  '62': 'Messaad',
  '63': 'Aïn Oussera',
  '64': 'Bou Saâda',
  '65': 'El Abiodh Sidi Cheikh',
  '66': 'El Kantara',
  '67': 'Bir El Ater',
  '68': 'Ksar El Boukhari',
  '69': 'El Aricha',
};

/** Resolve a 2-digit wilaya code to `{ code, name }`, or `undefined` if unknown. */
export function lookupWilaya(code: string): Wilaya | undefined {
  const name = WILAYAS[code];
  return name ? { code, name } : undefined;
}
